# Generated by Django 5.2.1 on 2025-05-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The actual text message for the reminder.')),
                ('reminder_datetime', models.DateTimeField(help_text='The specific date and time when the reminder should be triggered.')),
                ('delivery_method', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], default='EMAIL', help_text='How the user wants to be reminded (e.g., SMS, Email).', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the reminder was created in the system.')),
                ('is_sent', models.BooleanField(default=False, help_text='Flag to indicate if the reminder message has been sent.')),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['reminder_datetime', 'created_at'],
            },
        ),
    ]
